name: Swift

on: push

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-15

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: swift build --verbose

      # - name: Run executable
      #   run: swift run vz-nixos --help
